### ISSUE TITLE
issue 2

### ISSUE THREAD

**Issue by tommy16102** [tommy16102/Movie#2]
한 것
1. axios로 현재 상영영화(일별박스오피스), 개봉예정영화(전체영화에서 filter로 개봉예정인거 가져옴), 순위(주간,주중,주말)

해야하는 것
1. px -> %/em/rem
2. 로그인 state -> id/password구분하기
3. 기타 component로 더쪼개기
4. 영화 axios로 가져온거 css하기
5. 기타 등등

**Comment by hojunlee-hj** [comment]
great
